# Generated by Django 4.1 on 2023-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='consulting_content',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
