# Generated by Django 4.1 on 2023-04-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_consulting_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='consulting_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
