# Generated by Django 4.1 on 2023-04-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_consulting_consulting_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulting',
            name='create_date',
        ),
    ]
