# Generated by Django 4.1.7 on 2023-03-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Time_Table",),
    ]
