# Generated by Django 4.1.7 on 2023-03-03 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0003_time_table_reserve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserve",
            name="teacher_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qna.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="time",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qna.time_table",
            ),
        ),
    ]
