# Generated by Django 4.1 on 2023-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_alter_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
