# Generated by Django 4.1 on 2023-03-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_reserve_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
