# Generated by Django 4.1 on 2023-03-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_alter_reserve_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
