# Generated by Django 4.1 on 2023-03-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_remove_reserve_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='content',
            new_name='comment_content',
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='subject',
            new_name='comment_subject',
        ),
    ]
