# Generated by Django 4.1 on 2023-03-29 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0008_rename_content_reserve_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='comment_content',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='comment_subject',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_subject', models.CharField(max_length=50)),
                ('comment_content', models.TextField(max_length=10000)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qna.reserve')),
            ],
        ),
        migrations.AddField(
            model_name='reserve',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_comments', to='qna.comment'),
        ),
    ]
